version: '3'

services:
  # 前端应用
  frontend:
    image: ghcr.io/zuoa/jiadan-pic:main
    container_name: jiadan-pic-web
    restart: "always"
    depends_on:
      - backend
    ports:
      - "8000:8000"
    environment:
      - "TZ=Asia/Shanghai"
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - jiadan-network

  backend:
    image: ghcr.io/zuoa/jiadan-pic-api:main
    container_name: jiadan-pic-api
    environment:
      - NODE_ENV=production
      - "TZ=Asia/Shanghai"
    restart: unless-stopped
    networks:
      - jiadan-network

networks:
  jiadan-network:
    driver: bridge
